name: "CI/CD"

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "16" # Specify the Node.js version you are using

      - name: Install Dependencies
        run: |
          cd secondChance-backend
          npm install

      - name: Run ESLint
        run: |
          cd secondChance-backend
          npx eslint . --fix --config ./eslint.config.js
